# PowerShell Import Script
terraform import aws_s3_bucket.alb_logs pythonapp-alb-logs-dev-668227158023
terraform import aws_s3_bucket.cloudtrail_logs[0] pythonapp-cloudtrail-logs-dev-668227158023
terraform import aws_iam_role.eks_cluster pythonapp-eks-cluster-role-dev
terraform import aws_cloudwatch_log_group.eks_cluster /aws/eks/pythonapp-cluster-dev/cluster
terraform import aws_iam_role.eks_nodes pythonapp-eks-node-role-dev
terraform import aws_iam_role.ec2_instance pythonapp-ec2-instance-role-dev
terraform import aws_iam_role.rds_enhanced_monitoring pythonapp-rds-monitoring-role-dev
terraform import aws_iam_role.lambda_execution pythonapp-lambda-execution-role-dev
terraform import aws_cloudwatch_log_group.vpc_flow_logs[0] /aws/vpc/flow-logs/pythonapp-dev
terraform import aws_iam_role.vpc_flow_logs[0] pythonapp-vpc-flow-logs-dev
terraform import aws_db_subnet_group.main pythonapp-db-subnet-group-dev
